# To let the CI execute the maven wrapper, use this command and push the change:
#    git update-index --chmod=+x mvnw

language: java
install: true
jdk:
  - oraclejdk11

before_install:
  - openssl aes-256-cbc -K $encrypted_073a412aed2d_key -iv $encrypted_073a412aed2d_iv -in ci-settings.xml.enc -out ci-settings.xml -d

script:
  - ./mvnw clean install -X

deploy:
  - provider: script
    script: ./mvnw -s ci-settings.xml deploy -X
    skip_cleanup: true
    on:
      branch: master
      tags: true
  - provider: releases
    api_key:
      secure: "i01kkqrgk7GsoyPfr9Z63yGsII/HTt7qFbCYYKmf/AGKAH4GrFz3S2x4KDl+kjebt+MjMIxsY/PEyQUl0PoRqeaPwuIu+24grTYaHPQGF2NAcq5+X6EPCcXyAkX65u/YEmV0HwZ7EDiDasELuRkD4IpsXVVsgaEcHHMcJAoovYTOwPVhTNI6d7Icxye0PT0mdOSJH6kKBZZAto/1fcaBEvNiNnO81P8CPmvVcUEqW0FsiasIabFpWLIA0xlgbKQZYtjfTNc791IY6EFgF6Rj7C4G9RyXQfnYe9uBK/qe++D+iA0+UqLCawIf2+res+PGP1uaaILsh91mkElNEhAGpi/slm4lqGdtUaFZ+9VRCgpF2kzGL7yn8cY7ODnTzbgBzVhWnABjApqzsOv0OqwdjIHel1TTXWes43nPXs9hrayKbHx+7J0ftYc/cfAqVM4+rRyy0WJOapmfpt+HNRPtHy1WdZoJ4L8ZR33EmsxUivSD6FSP7dnq2ijvr52HuAfxtYiR9zewtdHEyILdPR0RbpAZccLt6MfbeC9N23r2WUfcHAuogcqrI6gujQV7thRurvFjEdGrI4dRQRezbP4IOUKsKBkyDITQ4X/qJo3SHtl6CsIH9mkdFJ5gwApSUljA41kQbiw6p755yzaDm4fNxVClt3XMV2/LZOz8lKBYbCk="
    file_glob: true
    file:
      - "target/*.jar"
    skip_cleanup: true
    on:
      branch: master
      tags: true

cache:
  directories:
    - $HOME/.m2

notifications:
  slack:
    secure: "LcsdbgzYCoTAg8gKygSkpaHhvjQPJSsbalqRxRSllhM/tvXAU9RBBRdrrp3O5scywbeJhm+RMopK16RLry5goyUly7lUXaGAsFAT9hUBTXL2p/BXT8jtGGQhjgQa1lt2PSqdf7oX4MDGq0nclJZUiHkilJTJ0dYBs6phAsFy1nmlLhgYGhmVjN+mRA1PvQLmDsRC3O5pe0N8FzEA9eVE54DBl9ElMSjYjk0dpyfjWk1xCRXYAQWa59scSJBt++DBespXrUI6H+cMx1Tigse/BtjFz7N8UvUcXoiv21QYxiKdF9faJL9cI+XHoaRDw0sgxB6xhOw+FWsCItX6qn2B6N7ieO2NkMFKR2XjOJ73ppPZhFSVMIcS+V+1lKRWfM9fdl/Rk8nAWYiFLS+On5xrW7hQbjOkPElQTkkNV1t7gNLytfkBHWmE70ckX4LjH9achgVRksnBflp3PWVXoANKSo5p95z9s4B0w0Y0X+kSnLRfYH6dy7+dnYDIngSIdkXghRJImZFFX9m9xWk32fMmbSiuN1y0/5tPVv5UIYPdtnX2ymajui+0qFvTktowuIl6Xz14EkqQqIX33F//URTcx8hGiMHXHZKvXgHRtWKXxEZT0qE+2U6fj9c02AraSvLIVnWJV5ty4j7hHT2LCyLYeG3Ip5H5U1oSDV1Mpn4CNWg="
  email: false
